In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split

In [0]:
iris = load_iris()

In [17]:
print(iris.feature_names)#attributes
print(iris.target_names)#class labels
print(iris.DESCR)#data set characteristics
print(iris.data)#prints data of iris

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high

In [0]:
input_data = iris.data #give iris dataset as input

In [20]:
target_class = iris.target #assign integer values to class labels
iris['target']
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [24]:
scaler = StandardScaler() #z-score normalizer
input_scaled = scaler.fit_transform(input_data) #apply z-score norm to input data
print(input_scaled)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [25]:
# One hot encoding
enc = OneHotEncoder() #convert categorical data to numeric array
hot_target_class = enc.fit_transform(target_class[:, np.newaxis]).toarray() #converts target names into numeric array
print(hot_target_class)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [26]:
x_train,x_test,y_train,y_test = train_test_split(input_scaled,hot_target_class,test_size=0.3) #split the input and target data into training and testing
x_train
x_test

array([[-1.74885626, -0.36217625, -1.34022653, -1.3154443 ],
       [ 0.31099753, -0.36217625,  0.53540856,  0.26414192],
       [-1.50652052,  1.24920112, -1.56757623, -1.3154443 ],
       [ 0.67450115, -0.59237301,  1.0469454 ,  1.31719939],
       [-0.90068117,  0.55861082, -1.16971425, -0.92054774],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ],
       [ 0.55333328,  0.55861082,  0.53540856,  0.52740629],
       [ 1.2803405 ,  0.09821729,  0.64908342,  0.3957741 ],
       [ 0.18982966, -0.13197948,  0.59224599,  0.79067065],
       [ 0.55333328, -0.36217625,  1.0469454 ,  0.79067065],
       [ 2.4920192 ,  1.70959465,  1.50164482,  1.05393502],
       [-1.02184904,  0.32841405, -1.45390138, -1.3154443 ],
       [ 0.18982966, -1.97355361,  0.13754657, -0.26238682],
       [ 1.64384411,  0.32841405,  1.27429511,  0.79067065],
       [ 1.03800476,  0.55861082,  1.10378283,  1.18556721],
       [ 1.15917263, -0.13197948,  0.99010798,  1.18556721],
       [-1.14301691, -1.

In [27]:
model = Sequential() #creating sequential model

W0820 05:52:16.164448 140675640702848 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [28]:
#add layers to the model using dense func
h1 = model.add(Dense(6,activation="relu",input_dim=4))
h2=model.add(Dense(5,activation="relu"))
h3=model.add(Dense(7,activation="relu"))
o = model.add(Dense(3,activation="softmax"))


W0820 05:52:37.300932 140675640702848 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 05:52:37.318121 140675640702848 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [29]:
#configuring the learning process
model.compile(loss="categorical_crossentropy",optimizer="Adam",metrics=['accuracy'])

W0820 05:52:57.637239 140675640702848 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0820 05:52:57.678229 140675640702848 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [30]:
#print the summary of the model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 30        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 35        
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 24        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [32]:
#fit the training data to the generated model
model.fit(x_train,y_train,batch_size=10,epochs=50)

Epoch 1/50
105/105 [==============================] - 0s 3ms/step - loss: 1.0766 - acc: 0.3238
Epoch 2/50
105/105 [==============================] - 0s 187us/step - loss: 1.0485 - acc: 0.3238
Epoch 3/50
105/105 [==============================] - 0s 184us/step - loss: 1.0214 - acc: 0.3333
Epoch 4/50
105/105 [==============================] - 0s 163us/step - loss: 0.9985 - acc: 0.3810
Epoch 5/50
105/105 [==============================] - 0s 183us/step - loss: 0.9789 - acc: 0.4286
Epoch 6/50
105/105 [==============================] - 0s 171us/step - loss: 0.9595 - acc: 0.4095
Epoch 7/50
105/105 [==============================] - 0s 189us/step - loss: 0.9407 - acc: 0.4190
Epoch 8/50
105/105 [==============================] - 0s 166us/step - loss: 0.9235 - acc: 0.4190
Epoch 9/50
105/105 [==============================] - 0s 176us/step - loss: 0.9073 - acc: 0.4476
Epoch 10/50
105/105 [==============================] - 0s 217us/step - loss: 0.8914 - acc: 0.4667
Epoch 11/50
105/105 [==========

In [33]:
 #predict the test data 
  score = model.evaluate(x_test,y_test, verbose=0)
 print('Test loss:', score[0])
 print('Test accuracy:', score[1])

Test loss: 0.3329682038889991
Test accuracy: 0.8444444484180874
