In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [0]:
model = Sequential()

In [0]:
model.add(Dense(2,activation="sigmoid",input_dim=3))
model.add(Dense(3,activation="sigmoid"))
model.add(Dense(2))

In [9]:
model.layers[0].get_weights()

[array([[ 0.00395048,  0.68499696],
        [ 0.25594783,  0.38824105],
        [ 0.09442759, -0.07780886]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [0]:
w12=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
b1=np.array([0.4,0.2])
weights1=[w12,b1]
weights1

model.layers[0].set_weights(weights1)

In [11]:
model.layers[1].get_weights()

[array([[ 0.5479046 ,  0.7115289 ,  0.5353215 ],
        [-0.2204678 , -0.9793549 , -0.03045785]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [0]:
w23=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
b2=np.array([0.1,0.1,0.2])
weights2=[w23,b2]
weights2

model.layers[1].set_weights(weights2)

In [13]:
model.layers[2].get_weights()

[array([[ 1.0785773 ,  0.6158184 ],
        [ 0.7821288 ,  1.0669653 ],
        [-0.59640443, -0.6418535 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [0]:
w34=np.array([[0.3,0.2],[-0.5,0.5],[-0.7,0.2]])
b4=np.array([0.1,0.2])
weights3=[w34,b4]
weights3

model.layers[2].set_weights(weights3)

In [0]:
from keras import optimizers
sgd = optimizers.SGD(lr=0.9)
model.compile(loss='mean_squared_error', optimizer=sgd,metrics=['accuracy'])

In [17]:
x=np.array([[1,0,1]])
y=np.array([[1,0]])
model.fit(x,y,epochs=1)

#from keras.callbacks import Callback
#cbk = CollectWeightCallback(layer_index=-1)
#model.fit(x, y, epochs=1, callbacks=[cbk])

Epoch 1/1
1/1 [==============================] - 0s 319ms/step - loss: 1.2860 - acc: 0.0000e+00


In [19]:
for i in range(3):
  print(model.layers[i].get_weights())
  
  print("\n\n")

[array([[ 0.14587797, -0.28498203],
       [ 0.4       ,  0.1       ],
       [-0.55412203,  0.21501799]], dtype=float32), array([0.34587798, 0.21501799], dtype=float32)]



[array([[-0.2648723 ,  0.0747495 ,  0.46942055],
       [-0.1648723 , -0.22525051, -0.3305795 ]], dtype=float32), array([ 0.16691256, -0.13858187, -0.04873271], dtype=float32)]



[array([[ 0.9004086 , -0.08166339],
       [ 0.2030983 ,  0.17016286],
       [ 0.08546948, -0.16847907]], dtype=float32), array([ 1.4067509 , -0.41302234], dtype=float32)]





In [0]:
wupdate1=[x1 - x2 for (x1, x2) in zip(weights1, model.layers[0].get_weights())]

In [21]:
wupdate1

[array([[ 5.41220278e-02, -1.50179744e-02],
        [-5.96046446e-09, -1.49011611e-09],
        [ 5.41220307e-02, -1.50179893e-02]]),
 array([ 0.05412202, -0.01501799])]

In [22]:
wupdate2=[x1 - x2 for (x1, x2) in zip(weights2, model.layers[1].get_weights())]
wupdate2

[array([[-0.03512769,  0.1252505 ,  0.13057945],
        [-0.0351277 ,  0.12525051,  0.13057949]]),
 array([-0.06691256,  0.23858187,  0.24873271])]

In [23]:
wupdate3=[x1 - x2 for (x1, x2) in zip(weights3, model.layers[2].get_weights())]
wupdate3

[array([[-0.60040863,  0.28166339],
        [-0.7030983 ,  0.32983714],
        [-0.78546948,  0.36847907]]), array([-1.30675092,  0.61302234])]